url: https://teseu.github.io
baseurl: ""

# Site settings
title: Teseu on GitHub
email: teseu@tucano.net.br
description: "Site pessoal para a conta do github."


# Team names, titles and social links
people:
- name: Ludmilla Bizzotto Petrin
  pic: 1
  position: Suporte
  social:
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Teseu
  pic: teseu
  position: Querendo ser Coder
  social:
    - title: github
      url: #
    - title: wordpress
      url: #
    - title: twitter
      url: #

- name: Tulio Macedo
  pic: 3
  position: Sou eu
  social:
    - title: lastfm
      url: #
    - title: youtube
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/teseu
  - title: facebook
    url:
  - title: github
    url: http://github.com/tuliomac
  - title: wordpress
    url:
  - title: lastfm
    url:
  - title: youtube
    url:


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
